import {
  Timeline,
  TimelineConnector,
  TimelineContent,
  TimelineDot as MuiTimelineDot,
  TimelineDotProps,
  TimelineItem,
  timelineItemClasses,
  TimelineSeparator,
} from "@mui/lab";
import { Typography } from "@mui/material";
import { useAtom } from "jotai";
import { type NextPage } from "next";
import Head from "next/head";
import { BookChecker } from "./components/BookChecker";
import { CheckResults } from "./components/CheckResults";
import { FetchPages } from "./components/FetchPages";
import { checkResultsAtom } from "./store";

export const Home: NextPage = () => {
  const [checkResults, _] = useAtom(checkResultsAtom);
  return (
    <>
      <Head>
        <title>gBooks Downloader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          // backgroundImage: "linear-gradient(to top right, #fff , #2e026d);",
          paddingTop: "2rem",
        }}
      >
        <Timeline
          position="right"
          sx={{
            [`& .${timelineItemClasses.root}:before`]: { flex: 0, padding: 0 },
          }}
        >
          <TimelineItem>
            <TimelineSeparator>
              <TimelineDot color="primary" />
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent>
              <Typography variant="h5" component="h2">
                Check for your book
              </Typography>
              <BookChecker />
            </TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineSeparator>
              <TimelineDot color={checkResults ? "primary" : undefined} />
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent>
              <Typography variant="h5" component="h2">
                Book check Results
              </Typography>
              <CheckResults />
            </TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineSeparator>
              <TimelineDot color={checkResults ? "primary" : undefined} />
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent>
              <Typography variant="h5" component="h2">
                Fetch Available Pages
              </Typography>
              <FetchPages />
            </TimelineContent>
          </TimelineItem>
        </Timeline>
      </main>
    </>
  );
};

const TimelineDot = (props: TimelineDotProps) => (
  <MuiTimelineDot sx={{ mt: "17px" }} variant="outlined" {...props} />
);
